#new changes!!!!
print("CHEESE.")
print("=================================================")
input("Press enter to continue...")
print("\nIt is unknown when cheese was first made.\nThe earliest direct evidence for cheesemaking has been found in excavated clay sieves (holed pottery) dated to be over seven thousand years old;\nFor example in Kujawy, Poland, and the Dalmatian coast in Croatia, the latter with dried remains which chemical analysis suggests was cheese.\nShards of holed pottery were also found in Urnfield pile-dwellings on Lake Neuchatel in Switzerland and are hypothesized to be cheese-strainers;\nthey date back to roughly eight thousand years ago.\nFor preservation purposes, cheese-making may have begun by the pressing and salting of curdled milk.\nAnimal skins and inflated internal organs already provided storage vessels for a range of foodstuffs.\nCurdling milk in an animal's stomach made solid and better-textured curds when compared to other traditional storage methods, such as clay jars. "
      "\nHard salted cheese is likely to have accompanied dairying from the outset as it is the only form in which milk can be kept in a hot climate.\nDairying existed around 4,000 BC in the grasslands of the Sahara.\nCheese produced in Europe, where climates are cooler than in the Middle East, required less salt for preservation.\nWith less salt and acidity, the cheese became a suitable environment for useful microbes and molds, giving aged cheeses their pronounced and interesting flavors.")
print("=================================================")
input("Press enter to continue to the next exhibit...")
print("\nPANCAKE.")
print("=================================================")
input("Press enter to continue...")
print("\nThe Ancient Greeks made pancakes called τηγανίτης (tēganitēs), ταγηνίτης (tagēnitēs) or ταγηνίας (tagēnias), all words deriving from τάγηνον (tagēnon), \"frying pan\".\nThe earliest attested references to tagenias are in the works of the 5th-century BC poets Cratinus and Magnes.\nTagenites were made with wheat flour, olive oil, honey, and curdled milk, and were served for breakfast.\nAnother kind of pancake was σταιτίτης (staititēs), from σταίτινος (staitinos), \"of flour or dough of spelt\", derived from σταῖς (stais), \"flour of spelt\".\nAthenaeus mentions, in his Deipnosophistae, staititas topped with honey, sesame, and cheese.\nThe Middle English word pancake appears in English in the 15th century.\nThe Ancient Romans called their fried concoctions alia dulcia, Latin for \"other sweets\".\nThese were much different from what are known as pancakes today.")
print("=================================================")